// Copyright 2022 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image -i thintel15.png -f mono2`

#pragma once

#include <stdint.h>

extern const uint32_t oled_font_length;
extern const uint8_t oled_font[890];
